import Head from "next/head";
import Image from "next/image";
import styles from "./styles/Home.module.scss";
import Button from "./components/Button";
import Projects from "./components/Projects";

export default function Home() {
  return (
    <div style={{ position: "relative", top: 0, left: 0 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.buttonsContainer}>
          <Button active label="<Home />" />
          <Button label="<Jobs />" />
        </div>
        <div className={styles.buttonsContainer}>
          <Button label="<Projects />" />
          <Button label="<Skills />" />
        </div>
      </header>
      <main className={styles.main}>
        <div>
          <p className={styles.paragraph}>This is</p>
        </div>
        <div className={styles.headingContainer}>
          <p className={styles.heading}>Logan Thomas</p>
        </div>
        <div>
          <p className={styles.paragraph}>Full-stack Developer</p>
        </div>
      </main>
      <footer></footer>
      <div className={styles.line}></div>
      <div className={styles.line2}></div>
      <div className={styles.line3}></div>
      {/* <div className={styles.arrow}>&darr;</div> */}
      <button className={styles.downloadResume}>Download Resume</button>
      <div className={styles.line4}></div>
      {/* <Projects /> */}
    </div>
  );
}
