import Head from "next/head";
import Image from "next/image";
import styles from "./styles/Home.module.scss";
import Button from "./components/Button";
import Projects from "./components/Projects";
import Typewriter from "typewriter-effect";

export default function Home() {
  const openResume = () => {
    window
      .open(
        "https://www.canva.com/design/DAEhZ8vjuBc/EUMbAoelpyf8er338asyYw/view?utm_content=DAEhZ8vjuBc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
        "_blank"
      )
      ?.focus();
  };

  const typewriter = (typewriter: any) => {
    typewriter
      .typeString("Web")
      .pauseFor(1000)
      .deleteAll()
      .typeString("React")
      .pauseFor(1000)
      .deleteAll()
      .typeString("Full Stack")
      .pauseFor(1000)
      .deleteAll()
      .typeString("JavaScript")
      .pauseFor(1000)
      .deleteAll()
      .typeString("TypeScript")
      .pauseFor(1000)
      .deleteAll()
      .typeString("NextJS")
      .pauseFor(1000)
      .deleteAll()
      .start();
  };

  return (
    <div style={{ position: "relative", top: 0, left: 0, height: "100vh" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.buttonsContainer}>
          <Button active label="<Home />" />
          <Button label="<Jobs />" />
        </div>
        <div className={styles.buttonsContainer}>
          <Button label="<Projects />" />
          <Button label="<Skills />" />
        </div>
      </header>
      <main className={styles.main}>
        <div>
          <p className={styles.paragraph}>This is</p>
        </div>
        <div className={styles.headingContainer}>
          <p className={styles.heading}>Logan Thomas</p>
        </div>
        <div>
          <div className={styles.paragraph}>
            <Typewriter
              options={{ autoStart: true, loop: true }}
              onInit={typewriter}
            />
            Developer
          </div>
        </div>
      </main>
      <footer></footer>
      <div className={styles.line}></div>
      <div className={styles.line2}></div>
      <div className={styles.line3}></div>
      <div className={styles.line7}></div>
      {/* <div className={styles.arrow}>&darr;</div> */}
      <button className={styles.downloadResume} onClick={openResume}>
        Open Resume
      </button>
      <div className={styles.line4}></div>
      <div className={styles.line5}></div>
      <div className={styles.line6}></div>
      <Projects />
    </div>
  );
}
